Add configuration file for PHP 8.2 images
mailpoet/wordpress-images pull request #48
Opened 2023-10-16 18:52 UTC by rodrigoprimo

I'm assuming there is no reason to keep the 8.2 RC6 configuration files as it was just a temporary solution, and that is why I opted to rename it to 8.2 instead of creating a new folder and keeping the 8.2 RC6 one.

Here are the published images:

https://hub.docker.com/layers/mailpoet/wordpress/8.2_20231016.1/images/sha256-07e1142cda715999365ce80789d4c75a50b87e59ea50de86aae7bfa40e16b5a2?context=explore
https://hub.docker.com/layers/mailpoet/wordpress/8.2-cli_20231016.1/images/sha256-d0573fe21c81e092adfbb136540942f2fddfa5b53e14536dede289d7db973f97?context=explore

[MAILPOET-4620]

2023-10-17 17:51 UTC, brezocordero requested changes
@rodrigoprimo 
I noticed a mismatch in `libapache2-mod-php8.1`

2023-10-17 17:51 UTC, brezocordero commented on 8.2/Dockerfile
> +  sudo apt-get install libapache2-mod-php8.1 php-mysql apache2 && \
```suggestion
  sudo apt-get install libapache2-mod-php8.2 php-mysql apache2 && \
```

2023-10-18 12:38 UTC, rodrigoprimo commented
Good catch, @brezocordero. I fixed the version and rebuild the image.

2023-10-18 17:32 UTC, brezocordero approved these changes
LGTM!
Thanks for the fix.

2023-10-18 17:34 UTC, brezocordero commented
@rodrigoprimo I was going to rebase and merge but are we still using the 8.2 RC6?

2023-10-19 11:08 UTC, rodrigoprimo commented
@brezocordero, I don't think we are, and even if we are, removing the configuration files should not affect anything as the tags will continue to exist in Docker Hub.

We do have PHP 8.2 RC6 as an option in our dev env but that doesn't use one of our images: https://github.com/mailpoet/mailpoet/blob/trunk/dev/php82/Dockerfile#L1

2023-10-20 15:21 UTC, merged